name: Rust Test

on: [push]

jobs:
 test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Standard Tests
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Multicore Logic Tests
        uses: actions-rs/cargo@v1
        with:
          command: test --features=multicore
  